import type { Client, Driver, Truck, Trailer, CashBox, BankAccount, TripOrder, Provider, TransportRoute, Invoice } from '@/types/database';

export const DEFAULT_CLIENTS: Client[] = [
  {
    id: 101,
    name: 'AGRI-EXPORT NORD SARL',
    ice: '001928374000082',
    phone: '+212 539 94 12 30',
    email: 'contact@agri-export-nord.ma',
    address: 'Zone Franche de Tanger, Lot 45, Tanger',
    city: 'Tanger',
    currency: 'EUR',
    client_type: 'export',
    is_active: true,
    invoice_with_tva: true,
    shipping_address_line1: 'Zone Franche de Tanger, Lot 45',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Tanger',
    shipping_postal_code: '90000',
    shipping_country: 'Morocco',
    billing_address_line1: 'Zone Franche de Tanger, Lot 45',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Tanger',
    billing_postal_code: '90000',
    billing_country: 'Morocco',
    created_at: new Date().toISOString(),
  },
  {
    id: 102,
    name: 'BERRY MED TANGER',
    ice: '002847192000045',
    phone: '+212 539 39 88 11',
    email: 'logistics@berrymed.com',
    address: 'Route de Rabat, Km 12, Tanger',
    city: 'Tanger',
    currency: 'EUR',
    client_type: 'export',
    is_active: true,
    invoice_with_tva: true,
    shipping_address_line1: 'Route de Rabat, Km 12',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Tanger',
    shipping_postal_code: '90000',
    shipping_country: 'Morocco',
    billing_address_line1: 'Route de Rabat, Km 12',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Tanger',
    billing_postal_code: '90000',
    billing_country: 'Morocco',
    created_at: new Date().toISOString(),
  },
  {
    id: 103,
    name: 'FRIGO ATLANTIC AGADIR',
    ice: '003194827000091',
    phone: '+212 528 84 55 20',
    email: 'expeditions@frigoatlantic.ma',
    address: 'Zone Industrielle Anza, Agadir',
    city: 'Agadir',
    currency: 'MAD',
    client_type: 'export',
    is_active: true,
    invoice_with_tva: true,
    shipping_address_line1: 'Zone Industrielle Anza',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Agadir',
    shipping_postal_code: '80000',
    shipping_country: 'Morocco',
    billing_address_line1: 'Zone Industrielle Anza',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Agadir',
    billing_postal_code: '80000',
    billing_country: 'Morocco',
    created_at: new Date().toISOString(),
  },
  {
    id: 104,
    name: 'EURO-PRIMEURS LOGISTICS (PERPIGNAN)',
    ice: 'FR84920194820',
    phone: '+33 4 68 85 20 00',
    email: 'reception@europrimeurs-stcharles.fr',
    address: 'Grand Saint-Charles, 66000 Perpignan',
    city: 'Perpignan',
    currency: 'EUR',
    client_type: 'export',
    is_active: true,
    invoice_with_tva: false,
    shipping_address_line1: 'Grand Saint-Charles',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Perpignan',
    shipping_postal_code: '66000',
    shipping_country: 'France',
    billing_address_line1: 'Grand Saint-Charles',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Perpignan',
    billing_postal_code: '66000',
    billing_country: 'France',
    created_at: new Date().toISOString(),
  },
  {
    id: 105,
    name: 'IBERIA LOGISTICA VALENCIA S.L.',
    ice: 'ESB94820194',
    phone: '+34 96 150 44 22',
    email: 'trafico@iberialogistica.es',
    address: 'Polígono Industrial Fuente del Jarro, Valencia',
    city: 'Valencia',
    currency: 'EUR',
    client_type: 'import',
    is_active: true,
    invoice_with_tva: false,
    shipping_address_line1: 'Polígono Industrial Fuente del Jarro',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Valencia',
    shipping_postal_code: '46988',
    shipping_country: 'Spain',
    billing_address_line1: 'Polígono Industrial Fuente del Jarro',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Valencia',
    billing_postal_code: '46988',
    billing_country: 'Spain',
    created_at: new Date().toISOString(),
  },
  {
    id: 106,
    name: 'SOCIETE MAROCAINE DE TEXTILE (SOMATEX)',
    ice: '001594830000012',
    phone: '+212 522 30 11 44',
    email: 'import-export@somatex.ma',
    address: 'Quartier Industriel Ain Sebaa, Casablanca',
    city: 'Casablanca',
    currency: 'MAD',
    client_type: 'import',
    is_active: true,
    invoice_with_tva: true,
    shipping_address_line1: 'Quartier Industriel Ain Sebaa',
    shipping_address_line2: '',
    shipping_address_line3: '',
    shipping_address_line4: '',
    shipping_city: 'Casablanca',
    shipping_postal_code: '20250',
    shipping_country: 'Morocco',
    billing_address_line1: 'Quartier Industriel Ain Sebaa',
    billing_address_line2: '',
    billing_address_line3: '',
    billing_address_line4: '',
    billing_city: 'Casablanca',
    billing_postal_code: '20250',
    billing_country: 'Morocco',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_DRIVERS: Driver[] = [
  {
    id: 201,
    name: 'محمد العلمي (Mohamed El Alami)',
    phone: '+212 661 24 55 89',
    license: 'B/C/EC-48201',
    status: 'active',
    base_salary: 6500,
    bonus_percentage: 5,
    has_valid_visa: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 202,
    name: 'رشيد بنجلون (Rachid Benjelloun)',
    phone: '+212 663 88 19 40',
    license: 'B/C/EC-39281',
    status: 'active',
    base_salary: 6800,
    bonus_percentage: 5,
    has_valid_visa: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 203,
    name: 'يوسف التازي (Youssef Tazi)',
    phone: '+212 670 11 49 32',
    license: 'B/C/EC-59201',
    status: 'active',
    base_salary: 6200,
    bonus_percentage: 4,
    has_valid_visa: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 204,
    name: 'عمر الصنهاجي (Omar Senhaji)',
    phone: '+212 662 90 33 15',
    license: 'B/C/EC-94820',
    status: 'active',
    base_salary: 6400,
    bonus_percentage: 5,
    has_valid_visa: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 205,
    name: 'عبد الكريم الخمليشي (Abdelkrim Khamlichi)',
    phone: '+212 668 44 77 90',
    license: 'B/C/EC-82710',
    status: 'active',
    base_salary: 6000,
    bonus_percentage: 4,
    has_valid_visa: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_TRUCKS: Truck[] = [
  {
    id: 301,
    plate_number: '12345-A-40',
    model: 'Volvo FH 500 Euro 6',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 302,
    plate_number: '67890-B-40',
    model: 'Scania R 500 V8',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 303,
    plate_number: '11223-D-26',
    model: 'Mercedes Actros 1848',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 304,
    plate_number: '44556-A-40',
    model: 'Renault Trucks T-High 480',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 305,
    plate_number: '77889-H-40',
    model: 'MAN TGX 18.510',
    status: 'active',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_TRAILERS: Trailer[] = [
  {
    id: 401,
    plate_number: 'REM-8921-MA',
    model: 'Schmitz Cargobull Frigo S.KO COOL',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 402,
    plate_number: 'REM-4402-MA',
    model: 'Krone Cool Liner Carrier Vector',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 403,
    plate_number: 'REM-1193-MA',
    model: 'Lamberet SR2 Futura Frigo',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 404,
    plate_number: 'REM-7750-MA',
    model: 'Schmitz Tautliner Bâchée',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 405,
    plate_number: 'REM-9931-MA',
    model: 'Chereau Inogam Frigo Bi-Température',
    status: 'active',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_PROVIDERS: Provider[] = [
  {
    id: 501,
    name: 'Garage Poids Lourds Tanger Med',
    type: 'workshop',
    phone: '+212 539 93 40 10',
    email: 'contact@pl-tangermed.ma',
    address: 'Zone Franche Logistique, Tanger Med',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 502,
    name: 'Pneumatiques & Services Maroc (Michelin/Bridgestone)',
    type: 'tires',
    phone: '+212 522 40 55 60',
    email: 'ventes@pneus-services.ma',
    address: 'Route Côtière 111, Ain Sebaa, Casablanca',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 503,
    name: 'Thermo King Service Europe (Algeciras)',
    type: 'frigo_maintenance',
    phone: '+34 956 65 20 30',
    email: 'taller@thermoking-algeciras.es',
    address: 'Polígono Industrial La Menacha, Algeciras',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 504,
    name: 'FRS / DFDS Ferries Morocco',
    type: 'ferry',
    phone: '+212 539 94 26 12',
    email: 'freight@frs.es',
    address: 'Gare Maritime Tanger Med',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 505,
    name: 'Balearia Ferry Cargo',
    type: 'ferry',
    phone: '+34 902 160 180',
    email: 'cargo@balearia.com',
    address: 'Puerto Bahía de Algeciras',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 601,
    name: 'Attijariwafa Bank (MAD)',
    bank_name: 'Attijariwafa Bank',
    account_number: '007 640 0001234567890123 45',
    currency: 'MAD',
    account_type: 'current',
    current_balance: 450000,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 602,
    name: 'Attijariwafa Bank (EUR)',
    bank_name: 'Attijariwafa Bank',
    account_number: '007 640 0009876543210987 88',
    currency: 'EUR',
    account_type: 'current',
    current_balance: 42500,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 603,
    name: 'Banque Populaire (MAD)',
    bank_name: 'Banque Populaire',
    account_number: '101 780 2121123456789012 30',
    currency: 'MAD',
    account_type: 'current',
    current_balance: 280000,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 604,
    name: 'BMCE Bank of Africa (EUR)',
    bank_name: 'BMCE Bank of Africa',
    account_number: '011 780 0000554433221100 12',
    currency: 'EUR',
    account_type: 'current',
    current_balance: 25000,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_CASH_BOXES: CashBox[] = [
  {
    id: 701,
    name: 'صندوق الخزينة الرئيسي (Tanger Bureau MAD)',
    code: 'caisse_principale',
    currency: 'MAD',
    created_at: new Date().toISOString(),
  },
  {
    id: 702,
    name: 'صندوق الخزينة الأوروبي (Caisse EUR Bureau)',
    code: 'caisse_eur',
    currency: 'EUR',
    created_at: new Date().toISOString(),
  },
  {
    id: 703,
    name: 'صندوق مصروفات السائقين والسلف الطارئة (MAD)',
    code: 'caisse_chauffeurs',
    currency: 'MAD',
    created_at: new Date().toISOString(),
  },
  {
    id: 704,
    name: 'صندوق عهدة ميناء طنجة المتوسط (Tanger Med Port MAD)',
    code: 'caisse_port_tm',
    currency: 'MAD',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_TRIPS: TripOrder[] = [
  {
    id: 1001,
    route: 'Tanger (MA) -> Perpignan (FR)',
    route_export: 'طنجة (MA) -> بربينيان (FR)',
    route_import: 'فالنسيا (ES) -> الدار البيضاء (MA)',
    client_id: 101,
    client_import_id: 105,
    driver_id: 201,
    truck_id: 301,
    trailer_id: 401,
    departure_date: new Date().toISOString().split('T')[0],
    price: 34000,
    price_export: 34000,
    price_import: 22000,
    status: 'in_transit',
    created_at: new Date().toISOString(),
  },
  {
    id: 1002,
    route: 'Agadir (MA) -> Rotterdam (NL)',
    route_export: 'أكادير (MA) -> روتردام (NL)',
    route_import: 'مدريد (ES) -> طنجة (MA)',
    client_id: 103,
    client_import_id: 106,
    driver_id: 202,
    truck_id: 302,
    trailer_id: 402,
    departure_date: new Date().toISOString().split('T')[0],
    price: 48000,
    price_export: 48000,
    price_import: 19000,
    status: 'customs_export',
    created_at: new Date().toISOString(),
  },
  {
    id: 1003,
    route: 'Casablanca (MA) -> Valencia (ES)',
    route_export: 'الدار البيضاء (MA) -> فالنسيا (ES)',
    route_import: 'برشلونة (ES) -> القنيطرة (MA)',
    client_id: 102,
    client_import_id: 106,
    driver_id: 203,
    truck_id: 303,
    trailer_id: 404,
    departure_date: new Date().toISOString().split('T')[0],
    price: 28000,
    price_export: 28000,
    price_import: 24000,
    status: 'planned',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_ROUTES: TransportRoute[] = [
  {
    id: 1,
    name: 'طنجة → ألميريا',
    route_type: 'outbound',
    origin: 'طنجة',
    destination: 'ألميريا',
    origin_latitude: 35.7595,
    origin_longitude: -5.8340,
    destination_latitude: 36.8423,
    destination_longitude: -2.4623,
    distance_km: 180,
    estimated_days: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'طنجة → مرسيليا',
    route_type: 'outbound',
    origin: 'طنجة',
    destination: 'مرسيليا',
    origin_latitude: 35.7595,
    origin_longitude: -5.8340,
    destination_latitude: 43.2965,
    destination_longitude: 5.3698,
    distance_km: 1200,
    estimated_days: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'الدار البيضاء → برشلونة',
    route_type: 'outbound',
    origin: 'الدار البيضاء',
    destination: 'برشلونة',
    origin_latitude: 33.5731,
    origin_longitude: -7.5898,
    destination_latitude: 41.3851,
    destination_longitude: 2.1734,
    distance_km: 1100,
    estimated_days: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'طنجة → فالنسيا',
    route_type: 'outbound',
    origin: 'طنجة',
    destination: 'فالنسيا',
    origin_latitude: 35.7595,
    origin_longitude: -5.8340,
    destination_latitude: 39.4699,
    destination_longitude: -0.3763,
    distance_km: 950,
    estimated_days: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'ألميريا → طنجة',
    route_type: 'return',
    origin: 'ألميريا',
    destination: 'طنجة',
    origin_latitude: 36.8423,
    origin_longitude: -2.4623,
    destination_latitude: 35.7595,
    destination_longitude: -5.8340,
    distance_km: 180,
    estimated_days: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'مرسيليا → طنجة',
    route_type: 'return',
    origin: 'مرسيليا',
    destination: 'طنجة',
    origin_latitude: 43.2965,
    origin_longitude: 5.3698,
    destination_latitude: 35.7595,
    destination_longitude: -5.8340,
    distance_km: 1200,
    estimated_days: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'برشلونة → الدار البيضاء',
    route_type: 'return',
    origin: 'برشلونة',
    destination: 'الدار البيضاء',
    origin_latitude: 41.3851,
    origin_longitude: 2.1734,
    destination_latitude: 33.5731,
    destination_longitude: -7.5898,
    distance_km: 1100,
    estimated_days: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'فالنسيا → طنجة',
    route_type: 'return',
    origin: 'فالنسيا',
    destination: 'طنجة',
    origin_latitude: 39.4699,
    origin_longitude: -0.3763,
    destination_latitude: 35.7595,
    destination_longitude: -5.8340,
    distance_km: 950,
    estimated_days: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_INVOICES: Invoice[] = [
  {
    id: 1001,
    client_id: '104', // RENAULT TANGER MED SUPPLIER
    invoice_number: 'FAC-2025-1002',
    total_amount: '17500',
    paid_amount: '0',
    status: 'overdue',
    issue_date: '2025-08-20',
    due_date: '2025-09-08',
    bank_account_id: '501',
    currency: 'MAD',
    input_mode: 'ht_tva',
    ht_amount: '14583.33',
    tva_rate: '20',
    tva_amount: '2916.67',
    ttc_amount: '17500',
    route: 'طنجة (MA) -> فالنسيا (ES)',
    trip_order_id: 1001,
    payment_request_ref: 'DEM-2025-089',
    created_at: '2025-08-20T10:00:00Z',
  },
  {
    id: 1002,
    client_id: '103', // INDITEX MAROC LOGISTICS
    invoice_number: 'FAC-2025-2002',
    total_amount: '16000',
    paid_amount: '0',
    status: 'overdue',
    issue_date: '2025-08-25',
    due_date: '2025-09-11',
    bank_account_id: '502',
    currency: 'EUR',
    input_mode: 'ht_tva',
    ht_amount: '16000',
    tva_rate: '0',
    tva_amount: '0',
    ttc_amount: '16000',
    route: 'طنجة (MA) -> ألميريا (ES)',
    trip_order_id: 1002,
    payment_request_ref: 'DEM-2025-092',
    created_at: '2025-08-25T11:30:00Z',
  },
  {
    id: 1003,
    client_id: '101', // AGRI-EXPORT NORD SARL
    invoice_number: 'FAC-2025-3001',
    total_amount: '45000',
    paid_amount: '45000',
    status: 'paid',
    issue_date: '2025-09-01',
    due_date: '2025-09-30',
    bank_account_id: '501',
    currency: 'MAD',
    input_mode: 'ht_tva',
    ht_amount: '37500',
    tva_rate: '20',
    tva_amount: '7500',
    ttc_amount: '45000',
    route: 'طنجة (MA) -> مرسيليا (FR)',
    trip_order_id: 1001,
    payment_request_ref: 'DEM-2025-101',
    created_at: '2025-09-01T09:00:00Z',
  },
  {
    id: 1004,
    client_id: '102', // BERRY MED TANGER
    invoice_number: 'FAC-2025-3002',
    total_amount: '32000',
    paid_amount: '12000',
    status: 'partially_paid',
    issue_date: '2025-09-02',
    due_date: '2025-10-02',
    bank_account_id: '501',
    currency: 'MAD',
    input_mode: 'ht_tva',
    ht_amount: '26666.67',
    tva_rate: '20',
    tva_amount: '5333.33',
    ttc_amount: '32000',
    route: 'الدار البيضاء (MA) -> برشلونة (ES)',
    trip_order_id: 1003,
    payment_request_ref: 'DEM-2025-102',
    created_at: '2025-09-02T14:00:00Z',
  },
  {
    id: 1005,
    client_id: '105', // SEAT MAROC DISTRIBUTION
    invoice_number: 'FAC-2025-3003',
    total_amount: '22000',
    paid_amount: '0',
    status: 'unpaid',
    issue_date: '2025-09-03',
    due_date: '2025-10-03',
    bank_account_id: '501',
    currency: 'MAD',
    input_mode: 'ht_tva',
    ht_amount: '18333.33',
    tva_rate: '20',
    tva_amount: '3666.67',
    ttc_amount: '22000',
    route: 'طنجة (MA) -> مدريد (ES)',
    trip_order_id: 1004,
    payment_request_ref: 'DEM-2025-103',
    created_at: '2025-09-03T16:00:00Z',
  },
];

/**
 * Utility helper that safely falls back to default datasets when DB arrays are empty or undefined.
 */
export function fallbackArray<T>(dbData: T[] | null | undefined, defaultData: T[]): T[] {
  if (Array.isArray(dbData) && dbData.length > 0) {
    return dbData;
  }
  return defaultData;
}
