import type { SidebarGroup } from '@/components/sidebar';
import {
  LayoutDashboard,
  Truck,
  MapPin,
  Users,
  FileText,
  Calculator,
  Wrench,
  Settings,
  Bell,
  MessageSquare,
  Route,
  DollarSign,
  Car,
  Fuel,
  ClipboardList,
  AlertTriangle,
  ShieldCheck,
  BarChart3,
  Globe,
} from 'lucide-react';

export const navigationGroups: SidebarGroup[] = [
  {
    id: 'main',
    label: 'الرئيسية',
    labelFr: 'Principal',
    icon: <LayoutDashboard className="w-4 h-4" />,
    defaultOpen: true,
    items: [
      {
        title: 'لوحة التحكم',
        titleFr: 'Tableau de bord',
        href: '/dashboard',
        icon: <LayoutDashboard className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'operations',
    label: 'العمليات',
    labelFr: 'Opérations',
    icon: <MapPin className="w-4 h-4" />,
    defaultOpen: true,
    items: [
      {
        title: 'إدارة الرحلات',
        titleFr: 'Gestion des trajets',
        href: '/trips',
        icon: <MapPin className="w-4 h-4" />,
      },
      {
        title: 'تتبع الشاحنات',
        titleFr: 'Suivi des camions',
        href: '/truck-tracking',
        icon: <Truck className="w-4 h-4" />,
      },
      {
        title: 'مخططات الرحلات',
        titleFr: 'Itinéraires',
        href: '/transport-routes',
        icon: <Route className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'fleet',
    label: 'الأسطول والمركبات',
    labelFr: 'Flotte & Véhicules',
    icon: <Truck className="w-4 h-4" />,
    defaultOpen: true,
    items: [
      {
        title: 'الأسطول',
        titleFr: 'Flotte',
        href: '/fleet',
        icon: <Truck className="w-4 h-4" />,
      },
      {
        title: 'الصيانة',
        titleFr: 'Maintenance',
        href: '/maintenance',
        icon: <Wrench className="w-4 h-4" />,
      },
      {
        title: 'محركات الوقود',
        titleFr: 'Carburant',
        href: '/fuel-analytics',
        icon: <Fuel className="w-4 h-4" />,
      },
      {
        title: 'سندات الصيانة',
        titleFr: 'Bon de réparation',
        href: '/fuel-receipt',
        icon: <FileText className="w-4 h-4" />,
      },
      {
        title: 'نفقات العبّارات',
        titleFr: 'Ferries',
        href: '/ferry-expenses',
        icon: <Globe className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'people',
    label: 'الأشخاص',
    labelFr: 'Personnes',
    icon: <Users className="w-4 h-4" />,
    items: [
      {
        title: 'السائقين',
        titleFr: 'Chauffeurs',
        href: '/drivers',
        icon: <Users className="w-4 h-4" />,
      },
      {
        title: 'العملاء',
        titleFr: 'Clients',
        href: '/clients',
        icon: <Users className="w-4 h-4" />,
      },
      {
        title: 'المزوّدين',
        titleFr: 'Fournisseurs',
        href: '/providers',
        icon: <Car className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'finance',
    label: 'المالية والفواتير',
    labelFr: 'Finance & Facturation',
    icon: <DollarSign className="w-4 h-4" />,
    items: [
      {
        title: 'الفواتير',
        titleFr: 'Factures',
        href: '/invoices',
        icon: <FileText className="w-4 h-4" />,
      },
      {
        title: 'الخزينة والبنك',
        titleFr: 'Trésorerie',
        href: '/treasury',
        icon: <DollarSign className="w-4 h-4" />,
      },
      {
        title: 'المطابقة البنكية',
        titleFr: 'Rapprochement',
        href: '/bank-reconciliation',
        icon: <Calculator className="w-4 h-4" />,
      },
      {
        title: 'صرف العملات',
        titleFr: 'Change',
        href: '/forex',
        icon: <Globe className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'reports',
    label: 'التقارير',
    labelFr: 'Rapports',
    icon: <BarChart3 className="w-4 h-4" />,
    items: [
      {
        title: 'التقارير',
        titleFr: 'Rapports',
        href: '/reports',
        icon: <BarChart3 className="w-4 h-4" />,
      },
      {
        title: 'تقارير متقدمة',
        titleFr: 'Rapports avancés',
        href: '/advanced-reports',
        icon: <BarChart3 className="w-4 h-4" />,
      },
      {
        title: 'ربحية الرحلات',
        titleFr: 'Rentabilité',
        href: '/trip-profitability',
        icon: <Calculator className="w-4 h-4" />,
      },
      {
        title: 'لوحة المدراء',
        titleFr: 'Direction',
        href: '/executive-dashboard',
        icon: <LayoutDashboard className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
    ],
  },
  {
    id: 'documents',
    label: 'الوثائق',
    labelFr: 'Documents',
    icon: <FileText className="w-4 h-4" />,
    items: [
      {
        title: 'إدارة الوثائق',
        titleFr: 'Documents',
        href: '/documents',
        icon: <FileText className="w-4 h-4" />,
      },
      {
        title: 'تنبيهات الانتهاء',
        titleFr: 'Alertes expiration',
        href: '/notifications/expiration',
        icon: <AlertTriangle className="w-4 h-4" />,
      },
      {
        title: 'مناطق الحواجز',
        titleFr: 'Zones',
        href: '/geofence-zones',
        icon: <ShieldCheck className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'تنبيهات الحواجز',
        titleFr: 'Alertes geofence',
        href: '/geofence-alerts',
        icon: <AlertTriangle className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
    ],
  },
  {
    id: 'communication',
    label: 'التواصل',
    labelFr: 'Communication',
    icon: <MessageSquare className="w-4 h-4" />,
    items: [
      {
        title: 'إشعارات WhatsApp',
        titleFr: 'Notifications WhatsApp',
        href: '/whatsapp-notifications',
        icon: <Bell className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'تذكيرات WhatsApp',
        titleFr: 'Rappels WhatsApp',
        href: '/whatsapp-reminders',
        icon: <MessageSquare className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'المحادثات',
        titleFr: 'Discussions',
        href: '/chat',
        icon: <MessageSquare className="w-4 h-4" />,
      },
    ],
  },
  {
    id: 'driver',
    label: 'السائق',
    labelFr: 'Chauffeur',
    icon: <ClipboardList className="w-4 h-4" />,
    items: [
      {
        title: 'مهام السائق',
        titleFr: 'Tâches',
        href: '/driver-tasks',
        icon: <ClipboardList className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'سلف السائق',
        titleFr: 'Avances',
        href: '/driver-advances',
        icon: <DollarSign className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'تسليم السائق',
        titleFr: 'Livraison',
        href: '/driver-delivery',
        icon: <ClipboardList className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'طلبات السلف',
        titleFr: 'Demandes avance',
        href: '/emergency-advance-requests',
        icon: <AlertTriangle className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'تسويات السائق',
        titleFr: 'Règlements',
        href: '/driver-settlements',
        icon: <Calculator className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
    ],
  },
  {
    id: 'settings',
    label: 'الإعدادات',
    labelFr: 'Paramètres',
    icon: <Settings className="w-4 h-4" />,
    items: [
      {
        title: 'إعدادات الشركة',
        titleFr: 'Paramètres',
        href: '/settings',
        icon: <Settings className="w-4 h-4" />,
      },
      {
        title: 'سجل التدقيق',
        titleFr: 'Audit',
        href: '/audit-logs',
        icon: <ShieldCheck className="w-4 h-4" />,
        roles: ['admin'],
      },
    ],
  },
];
