import type { SidebarGroup } from '@/components/sidebar';
import { Truck } from '@/components/icons/vehicle-icons';
import {
  LayoutDashboard,
  MapPin,
  Users,
  FileText,
  Calculator,
  Wrench,
  Settings,
  Bell,
  MessageSquare,
  Route,
  DollarSign,
  Car,
  Fuel,
  ClipboardList,
  AlertTriangle,
  Bug,
  ShieldCheck,
  BarChart3,
  Globe,
  Building2,
  FolderCog,
  TrendingUp,
  Sparkles,
} from 'lucide-react';

export const navigationGroups: SidebarGroup[] = [
  {
    id: 'super-admin',
    label: 'الإشراف العام',
    labelFr: 'Super Admin',
    labelEs: 'Superadministrador',
    icon: <ShieldCheck className="w-4 h-4" />,
    defaultOpen: true,
    roles: ['super_admin'],
    items: [
      {
        title: 'إدارة الشركات والاشتراكات',
        titleFr: 'Gestion des entreprises & abonnements',
        titleEs: 'Gestión de empresas y suscripciones',
        href: '/super-admin/companies',
        icon: <Building2 className="w-4 h-4" />,
        roles: ['super_admin'],
      },
      {
        title: 'تتبع مشاكل الإدخال والشاشات',
        titleFr: 'Suivi des anomalies & saisie',
        titleEs: 'Seguimiento de problemas y pantallas',
        href: '/super-admin/screen-issues',
        icon: <Bug className="w-4 h-4 text-amber-500" />,
        roles: ['super_admin'],
      },
    ],
  },
  {
    id: 'main',
    label: 'الرئيسية',
    labelFr: 'Principal',
    labelEs: 'Principal',
    icon: <LayoutDashboard className="w-4 h-4" />,
    defaultOpen: true,
    roles: ['admin', 'secretary', 'accountant', 'fleet_manager'],
    items: [
      {
        title: 'لوحة التحكم',
        titleFr: 'Tableau de bord',
        titleEs: 'Panel de control',
        href: '/dashboard',
        icon: <LayoutDashboard className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'operations',
    label: 'العمليات',
    labelFr: 'Opérations',
    labelEs: 'Operaciones',
    icon: <MapPin className="w-4 h-4" />,
    defaultOpen: true,
    roles: ['admin', 'secretary', 'accountant', 'fleet_manager'],
    items: [
      {
        title: 'إدارة الرحلات',
        titleFr: 'Gestion des trajets',
        titleEs: 'Gestión de viajes',
        href: '/trips',
        icon: <MapPin className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'تتبع الشاحنات',
        titleFr: 'Suivi des camions',
        titleEs: 'Seguimiento de camiones',
        href: '/truck-tracking',
        icon: <Truck className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'مخططات الرحلات',
        titleFr: 'Itinéraires',
        titleEs: 'Rutas de transporte',
        href: '/transport-routes',
        icon: <Route className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'التسعير الديناميكي الذكي',
        titleFr: 'Tarification dynamique',
        titleEs: 'Precios dinámicos',
        href: '/pricing',
        icon: <Calculator className="w-4 h-4 text-emerald-500" />,
        roles: ['admin', 'secretary', 'accountant', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'fleet',
    label: 'الأسطول والمركبات',
    labelFr: 'Flotte & Véhicules',
    labelEs: 'Flota y Vehículos',
    icon: <Truck className="w-4 h-4" />,
    defaultOpen: true,
    roles: ['admin', 'secretary', 'fleet_manager'],
    items: [
      {
        title: 'الأسطول',
        titleFr: 'Flotte',
        titleEs: 'Flota',
        href: '/fleet',
        icon: <Truck className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'الصيانة',
        titleFr: 'Maintenance',
        titleEs: 'Mantenimiento',
        href: '/maintenance',
        icon: <Wrench className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'محركات الوقود',
        titleFr: 'Carburant',
        titleEs: 'Combustible y consumo',
        href: '/fuel-analytics',
        icon: <Fuel className="w-4 h-4" />,
        roles: ['admin', 'fleet_manager'],
      },
      {
        title: 'سندات الصيانة والوقود',
        titleFr: 'Bon de réparation / carburant',
        titleEs: 'Vales de reparación / combustible',
        href: '/fuel-receipt',
        icon: <FileText className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'نفقات العبّارات',
        titleFr: 'Ferries',
        titleEs: 'Gastos de transbordador',
        href: '/ferry-expenses',
        icon: <Globe className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'people',
    label: 'الأشخاص',
    labelFr: 'Personnes',
    labelEs: 'Personal y Contactos',
    icon: <Users className="w-4 h-4" />,
    roles: ['admin', 'secretary', 'accountant', 'fleet_manager'],
    items: [
      {
        title: 'السائقين',
        titleFr: 'Chauffeurs',
        titleEs: 'Conductores',
        href: '/drivers',
        icon: <Users className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'العملاء',
        titleFr: 'Clients',
        titleEs: 'Clientes',
        href: '/clients',
        icon: <Users className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant'],
      },
      {
        title: 'المزوّدين',
        titleFr: 'Fournisseurs',
        titleEs: 'Proveedores',
        href: '/providers',
        icon: <Car className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'finance',
    label: 'المالية والفواتير',
    labelFr: 'Finance & Facturation',
    labelEs: 'Finanzas y Facturación',
    icon: <DollarSign className="w-4 h-4" />,
    roles: ['admin', 'secretary', 'driver', 'accountant'],
    items: [
      {
        title: 'الفواتير',
        titleFr: 'Factures',
        titleEs: 'Facturas',
        href: '/invoices',
        icon: <FileText className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant'],
      },
      {
        title: 'الخزينة والبنك',
        titleFr: 'Trésorerie',
        titleEs: 'Tesorería y bancos',
        href: '/treasury',
        icon: <DollarSign className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant'],
      },
      {
        title: 'المطابقة البنكية',
        titleFr: 'Rapprochement',
        titleEs: 'Conciliación bancaria',
        href: '/bank-reconciliation',
        icon: <Calculator className="w-4 h-4" />,
        roles: ['admin', 'accountant'],
      },
      {
        title: 'صرف العملات',
        titleFr: 'Change',
        titleEs: 'Cambio de divisas',
        href: '/forex',
        icon: <Globe className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant'],
      },
      {
        title: 'طلبات السلف العاجلة',
        titleFr: 'Demandes avance',
        titleEs: 'Solicitudes de anticipo urgente',
        href: '/emergency-advance-requests',
        icon: <AlertTriangle className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'driver', 'accountant'],
      },
      {
        title: 'تسويات السائق',
        titleFr: 'Règlements',
        titleEs: 'Liquidaciones del conductor',
        href: '/driver-settlements',
        icon: <Calculator className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'accountant'],
      },
    ],
  },
  {
    id: 'reports',
    label: 'التقارير',
    labelFr: 'Rapports',
    labelEs: 'Informes',
    icon: <BarChart3 className="w-4 h-4" />,
    roles: ['admin', 'accountant', 'fleet_manager'],
    items: [
      {
        title: 'التقارير',
        titleFr: 'Rapports',
        titleEs: 'Informes generales',
        href: '/reports',
        icon: <BarChart3 className="w-4 h-4" />,
        roles: ['admin', 'accountant'],
      },
      {
        title: 'تقارير متقدمة',
        titleFr: 'Rapports avancés',
        titleEs: 'Informes avanzados',
        href: '/advanced-reports',
        icon: <BarChart3 className="w-4 h-4" />,
        roles: ['admin', 'accountant'],
      },
      {
        title: 'ربحية الرحلات',
        titleFr: 'Rentabilité',
        titleEs: 'Rentabilidad de viajes',
        href: '/trip-profitability',
        icon: <Calculator className="w-4 h-4" />,
        roles: ['admin', 'accountant'],
      },
      {
        title: 'لوحة المدراء',
        titleFr: 'Direction',
        titleEs: 'Panel de direction',
        href: '/executive-dashboard',
        icon: <LayoutDashboard className="w-4 h-4" />,
        roles: ['admin'],
      },
      {
        title: 'التحليلات التنبؤية والتوسع',
        titleFr: 'Analyses prédictives',
        titleEs: 'Análisis predictivos',
        href: '/predictive-analytics',
        icon: <TrendingUp className="w-4 h-4 text-primary" />,
        roles: ['admin', 'accountant', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'documents',
    label: 'الوثائق',
    labelFr: 'Documents',
    labelEs: 'Documentos',
    icon: <FileText className="w-4 h-4" />,
    roles: ['admin', 'secretary', 'fleet_manager'],
    items: [
      {
        title: 'إدارة الوثائق',
        titleFr: 'Documents',
        titleEs: 'Gestión documental',
        href: '/documents',
        icon: <FileText className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'أنواع وثائق الأسطول',
        titleFr: 'Types de documents',
        titleEs: 'Tipos de documentos',
        href: '/documents/types',
        icon: <FolderCog className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'تنبيهات الانتهاء',
        titleFr: 'Alertes expiration',
        titleEs: 'Alertas de caducidad',
        href: '/notifications/expiration',
        icon: <AlertTriangle className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'مناطق الحواجز',
        titleFr: 'Zones',
        titleEs: 'Zonas geocercadas',
        href: '/geofence-zones',
        icon: <ShieldCheck className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
      {
        title: 'تنبيهات الحواجز',
        titleFr: 'Alertes geofence',
        titleEs: 'Alertas de geocerca',
        href: '/geofence-alerts',
        icon: <AlertTriangle className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'communication',
    label: 'التواصل',
    labelFr: 'Communication',
    labelEs: 'Comunicación',
    icon: <MessageSquare className="w-4 h-4" />,
    roles: ['admin', 'secretary', 'driver', 'accountant', 'fleet_manager'],
    items: [
      {
        title: 'إشعارات WhatsApp',
        titleFr: 'Notifications WhatsApp',
        titleEs: 'Notificaciones WhatsApp',
        href: '/whatsapp-notifications',
        icon: <Bell className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'تذكيرات WhatsApp',
        titleFr: 'Rappels WhatsApp',
        titleEs: 'Recordatorios WhatsApp',
        href: '/whatsapp-reminders',
        icon: <MessageSquare className="w-4 h-4" />,
        roles: ['admin', 'secretary'],
      },
      {
        title: 'المحادثات',
        titleFr: 'Discussions',
        titleEs: 'Conversaciones',
        href: '/chat',
        icon: <MessageSquare className="w-4 h-4" />,
        roles: ['admin', 'secretary', 'driver', 'accountant', 'fleet_manager'],
      },
    ],
  },
  {
    id: 'driver',
    label: 'السائق',
    labelFr: 'Chauffeur',
    labelEs: 'Conductor',
    icon: <ClipboardList className="w-4 h-4" />,
    defaultOpen: true,
    roles: ['driver'],
    items: [
      {
        title: 'مهام السائق',
        titleFr: 'Tâches',
        titleEs: 'Tareas del conductor',
        href: '/driver-tasks',
        icon: <ClipboardList className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'تسليم الشحنات',
        titleFr: 'Livraison',
        titleEs: 'Entrega de envíos',
        href: '/driver-delivery',
        icon: <ClipboardList className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'سلف السائق',
        titleFr: 'Avances',
        titleEs: 'Anticipos del conductor',
        href: '/driver-advances',
        icon: <DollarSign className="w-4 h-4" />,
        roles: ['driver'],
      },
      {
        title: 'سندات الوقود والصيانة',
        titleFr: 'Bon de carburant',
        titleEs: 'Vales de combustible y mantenimiento',
        href: '/fuel-receipt',
        icon: <FileText className="w-4 h-4" />,
        roles: ['driver'],
      },
    ],
  },
  {
    id: 'settings',
    label: 'الإعدادات',
    labelFr: 'Paramètres',
    labelEs: 'Configuración',
    icon: <Settings className="w-4 h-4" />,
    roles: ['admin'],
    items: [
      {
        title: 'إعدادات النظام',
        titleFr: 'Paramètres',
        titleEs: 'Configuración del sistema',
        href: '/settings',
        icon: <Settings className="w-4 h-4" />,
        roles: ['admin'],
      },
      {
        title: 'المستخدمين والصلاحيات',
        titleFr: 'Utilisateurs & Rôles',
        titleEs: 'Usuarios y permisos',
        href: '/users',
        icon: <Users className="w-4 h-4" />,
        roles: ['admin'],
      },
      {
        title: 'فروع ومقرات الشركة',
        titleFr: 'Agences & Hubs',
        titleEs: 'Sucursales y sedes',
        href: '/branches',
        icon: <Building2 className="w-4 h-4" />,
        roles: ['admin'],
      },
      {
        title: 'سجل التدقيق',
        titleFr: 'Audit',
        titleEs: 'Registro de auditoría',
        href: '/audit-logs',
        icon: <ShieldCheck className="w-4 h-4" />,
        roles: ['admin'],
      },
    ],
  },
];
