-- Fiscal Years table for closed accounting periods
-- Migration: 20260922_fiscal_years.sql

CREATE TABLE IF NOT EXISTS public.fiscal_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN DEFAULT false,
    is_closed BOOLEAN DEFAULT false,
    opening_balance_mad NUMERIC(15, 2) DEFAULT 0.00,
    opening_balance_eur NUMERIC(15, 2) DEFAULT 0.00,
    closed_at TIMESTAMPTZ,
    closed_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT check_fiscal_dates CHECK (end_date >= start_date)
);

ALTER TABLE public.fiscal_years ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant isolation: fiscal_years"
ON public.fiscal_years
FOR ALL
TO authenticated
USING (company_id = public.current_company_id())
WITH CHECK (company_id = public.current_company_id());

CREATE INDEX IF NOT EXISTS idx_fiscal_years_company_id
ON public.fiscal_years(company_id);

CREATE INDEX IF NOT EXISTS idx_fiscal_years_dates
ON public.fiscal_years(company_id, start_date, end_date);
