-- incidents table for international transport incident & claims management
CREATE TABLE IF NOT EXISTS public.incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id),
  trip_order_id BIGINT REFERENCES public.trip_orders(id),
  truck_id BIGINT REFERENCES public.trucks(id),
  trailer_id BIGINT REFERENCES public.trailers(id),
  driver_id BIGINT REFERENCES public.drivers(id),
  client_id BIGINT REFERENCES public.clients(id),
  incident_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'moderate',
  status TEXT NOT NULL DEFAULT 'open',
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  incident_date TEXT NOT NULL,
  estimated_cost NUMERIC DEFAULT 0,
  actual_cost NUMERIC DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'MAD',
  insurance_reference TEXT,
  police_report_number TEXT,
  customs_reference TEXT,
  resolution_notes TEXT,
  resolved_at TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incidents_company ON public.incidents(company_id);
CREATE INDEX IF NOT EXISTS idx_incidents_trip ON public.incidents(trip_order_id);
CREATE INDEX IF NOT EXISTS idx_incidents_driver ON public.incidents(driver_id);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_date ON public.incidents(incident_date);

ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "incidents_tenant_isolation" ON public.incidents
  FOR ALL USING (company_id = current_company_id());

CREATE POLICY "incidents_super_admin" ON public.incidents
  FOR ALL USING (auth.role() = 'service_role');
