-- incident_attachments table for storing photos, police reports, insurance documents
CREATE TABLE IF NOT EXISTS public.incident_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id BIGINT NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES public.companies(id),
  file_url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_type TEXT NOT NULL,
  file_size BIGINT,
  attachment_type TEXT NOT NULL DEFAULT 'photo',
  description TEXT,
  uploaded_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incident_attachments_incident ON public.incident_attachments(incident_id);
CREATE INDEX IF NOT EXISTS idx_incident_attachments_company ON public.incident_attachments(company_id);
CREATE INDEX IF NOT EXISTS idx_incident_attachments_type ON public.incident_attachments(attachment_type);

ALTER TABLE public.incident_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "incident_attachments_tenant_isolation" ON public.incident_attachments
  FOR ALL USING (company_id = current_company_id());

CREATE POLICY "incident_attachments_super_admin" ON public.incident_attachments
  FOR ALL USING (auth.role() = 'service_role');
